config/routes.rb
Rails.application.routes.draw do

resources :blog_posts

root 'blog_posts#index'

  get 'index' => 'practice#index'

  post 'index' => 'practice#index'

  get 'about' => 'practice#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

	validates :title, :blog_entry, presence: true
	validates :title, uniqueness: true, length: { maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

	before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
  	@blog_posts = BlogPost.all
  end

  def show
  end

  def edit
  end

  def new
  	@blog_post = BlogPost.new
  end

def create
	@blog_post = BlogPost.new(blog_post_params)

	respond_to do |format|
		if @blog_post.save
			format.html { redirect_to blog_post_url(@blog_post), notice:
				"Blog Post was created successfully."}
			else
				format.html {render :new}
			end
		end
	end

	def update

		respond_to do |format|
			if @blog_post.update(blog_post_params)
				format.html { redirect_to blog_post_url(@blog_post),
					"Blog post was updated successfullly!"}
				else
					format.html { render :edit }
				end
			end
		end

	def destory
		@blog_post.destroy

		respond_to do |format|
			format.html { redirect_to blog_posts_url, notice: "Your Blog Post was DESTROYYEDDDD!!!!!!"}

		end
	end

	private

	def set_blog_post
		@blog_post = BlogPost.find(params[:id])
	end

	def blog_post_params
		params.require(:blog_post).permit(:title, :blog_entry, :author)
	end

end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	#were not using nay varibles in the view
  	#so nothing to setup in here...yet...
  	@name = params[:name]
  end

  def about
  	#here well pull from thr query string
  	# and save that value in an instance varible
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
	<% if @blog_post.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this
		blog_post from being saved:</h2>

		<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="form-group">
		<%= form.text_field :title, class: "form-control", placeholder: "Blog Title...
		" %>
	</div>

	<div class="form-group">
		<%= form.text_field :author, class: "form-control", placeholder: "Your Name
		Here..." %>
	</div>

	<div class="form-group">
		<%= form.text_area :blog_entry, class: "form-control", rows: 12, placeholder:
		"Tell Us Something..." %>
	</div>

	<div class="actions">
		<%= form.submit "Post", class: "btn btn-primary" %>
	</div>
	<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@blog_post), class: "btn btn-info" %>
<%= link_to "All Blog Post", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1>Current Blog Posts</h1>

<div class="row">
	<% @blog_posts.each do |blog_post| %>
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<%= blog_post.title %>
				</div>
				<div class="panel-body">
					by <%= blog_post.author %><br>
					<p><%= blog_post.blog_entry %></p>
				</div>
				<div class="panel-footer">
					<%= link_to "Show", blog_post, class: "btn btn-info" %>
					<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %>
					<%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: {
						confirm: "Are you sure?"}, class: "btn btn-danger" %>

					</div>
				</div>
			</div>
		<% end %>
	</div>

	<%= link_to "New Blog Post", new_blog_post_path, class: "btn btn-success" %>

app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "All Blog Post", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="panel panel-primary">

	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>

	<div class="panel-body">
		<p><%= @blog_post.author %></p>
		<p><%= @blog_post.blog_entry %></p>
	</div>

	<div class="panel-footer">
		<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
		<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/practice/about.html.erb
<!--remember, internal stylesheet in not the best, 
	but we have no way to get a Ruby instance varible into a css file, 
	so we dont have much of an alternative here -->



<div id="color_me_in">
	<p>
		<%= @color %> BOX ACTIVATED!
	</p>
</div>

<%= form_tag index_path do %>
 <p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>
 <p><%= submit_tag :submit %></p>
<% end %>

<style>
	
	#color_me_in {
		background-color: <%= @color %>;
		color: white;
		width: 250px;
		height: 250px;
	}

</style>

app/views/practice/index.html.erb
<h1>Choose a Color!</h1>

<% if !@name.nil? %>
	<h2>Welcome, Back, <%= @name %></h2>
<% end %>

<p>
 <%= link_to "Red", about_path(color: "red") %>
</p>

<p>
 <%= link_to "Blue", about_path(color: "blue") %>
</p>

<p>
 <%= link_to "Green", about_path(color: "green") %>
</p>

<p>
 <%= link_to "Yellow", about_path(color: "yellow") %>
</p>